/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RecastLib */

#ifndef _Included_RecastLib
#define _Included_RecastLib

/* 
extern "C" {
  

	JNIEXPORT void JNICALL Java_RecastLib_hello
		(JNIEnv *, jobject);

 	 
 
	JNIEXPORT jint JNICALL Java_RecastLib_load
		(JNIEnv *, jobject, jstring);

		JNIEXPORT jint JNICALL Java_com_seasun_navmesh_RecastLib_load__Ljava_lang_String_2_3B
		(JNIEnv *, jobject, jstring, jbyteArray);

 
	JNIEXPORT jobject JNICALL Java_RecastLib_find
		(JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);
 

	JNIEXPORT void JNICALL Java_RecastLib_testPermance
		(JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);
}
*/
#endif
